import { useMemo, useState } from 'react'
import snapshotJson from './generated/pipeline.json'
import type { Snapshot } from './lib/types'
import { Board } from './components/Board'
import { Teams } from './components/Teams'
import { Activity } from './components/Activity'
import { ProspectDetail } from './components/ProspectDetail'

// Generated by scripts/build-data.mjs; the JSON is wider than TS can infer literally.
const snapshot = snapshotJson as unknown as Snapshot

const TABS = [
  { id: 'board', label: 'Pipeline' },
  { id: 'teams', label: 'Team progress' },
  { id: 'activity', label: 'Activity' },
] as const

type TabId = (typeof TABS)[number]['id']

export function App() {
  const [tab, setTab] = useState<TabId>('board')
  const [openSlug, setOpenSlug] = useState<string | null>(null)

  // Fixed per render pass so every relative date on screen agrees.
  const now = useMemo(() => new Date(), [])

  const selected = openSlug
    ? (snapshot.prospects.find((p) => p.slug === openSlug) ?? null)
    : null

  const generated = new Date(snapshot.generatedAt)

  return (
    <div className="shell">
      <header className="topbar">
        <div className="brand">
          <span className="brand-mark" />
          Viridia SDR <small>/ pipeline</small>
        </div>

        <nav className="tabs" role="tablist">
          {TABS.map((t) => (
            <button
              key={t.id}
              role="tab"
              className="tab"
              aria-selected={tab === t.id}
              onClick={() => setTab(t.id)}
            >
              {t.label}
            </button>
          ))}
        </nav>

        <div className="freshness" title={`Snapshot generated ${snapshot.generatedAt}`}>
          <span className="pulse" />
          {snapshot.prospectCount} prospects · read {generated.toLocaleTimeString()}
        </div>
      </header>

      <main className="main">
        {tab === 'board' ? <Board snapshot={snapshot} now={now} onOpen={setOpenSlug} /> : null}
        {tab === 'teams' ? <Teams snapshot={snapshot} now={now} onOpen={setOpenSlug} /> : null}
        {tab === 'activity' ? <Activity snapshot={snapshot} onOpen={setOpenSlug} /> : null}
      </main>

      {selected ? (
        <ProspectDetail prospect={selected} now={now} onClose={() => setOpenSlug(null)} />
      ) : null}
    </div>
  )
}
